version: '3.8'

services:
  rails:
    build: ./blog
    command: rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      DB_HOST: fdb
      DB_USER: root
      DB_PASSWORD: Svirin1234!
    volumes:
      - ROR_volume:/app
    depends_on:
      - phpmyadmin

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Svirin1234!
    volumes:
      - db_volume:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
volumes:
  db_volume:
  ROR_volume:
  
